config/routes.rb
Rails.application.routes.draw do
  root 'usuarios#index'
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sexo.rb
class Sexo < ApplicationRecord
  has_many :usuarios
end

app/models/tipo_de_usuario.rb
class TipoDeUsuario < ApplicationRecord
  has_many :usuarios
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :sexo
  belongs_to :tipo_de_usuario
  before_save { self.correo = correo.downcase }

  validates :nombre, presence: true, length: { maximum: 50 }
  validates :apellido, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :correo, presence: true, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
  VALID_PHONE_REGEX = /\d+/i
  validates :telefono, presence: true, length: { maximum: 10},
                      format: { with: VALID_PHONE_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.js
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.js 
        format.html { redirect_to root_url, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :correo, :telefono, :sexo_id, :tipo_de_usuario_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/usuarios/_form.html.erb
<div class="form-container row">
  <%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

    <ul>
      <% usuario.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :correo %>
    <%= form.text_field :correo, class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    <%= form.label :sexo_id %>
    <%= form.select(:sexo_id, options_for_select([['Maculino', 1], ['Femenino', 2]]), {}, {class: "form-control"}) %>
  </div>

  <div class="field form-group ">
    <%= form.label :tipo_de_usuario_id %>
    <%= form.select(:tipo_de_usuario_id, options_for_select([['Admin', 1], ['Usuario general', 2]]), {}, {class: "form-control"}) %>
  </div>

  <div class="form-btn">
    <div class="field">
      <%= form.submit yield(:button_text), class: "btn btn-primary" %>
    </div>

    <div class="field">
      <%= link_to 'Cerrar', '#', :onclick => 'closeForm()', class: "btn btn-primary" %>
    </div>
  </div>

  <% end %>
</div>

app/views/usuarios/_usuario.html.erb
<tr id="usuario_<%= usuario.id%>">
  <td><%= usuario.nombre %></td>
  <td><%= usuario.apellido %></td>
  <td><%= usuario.correo %></td>
  <td><%= usuario.telefono %></td>
  <% if usuario.sexo_id === 1%>
    <td> Masculino </td>
  <% elsif usuario.sexo_id === 2 %>
    <td> Femenino </td>
  <% end %>
  <% if usuario.tipo_de_usuario_id === 1 %>
    <td> Admin </td>
  <% elsif usuario.tipo_de_usuario_id === 2 %>
    <td> Usuario general </td>
  <% end %>
  <td><%= link_to 'Edit', edit_usuario_path(usuario), data: {remote: true }%></td>
  <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Estas seguro?', remote: true}, class: "delete"  %></td>
</tr>

app/views/usuarios/create.js.erb
$('.form-container').remove()
$('#new-user').show()
$('.new-link').show()
$('table#users tbody').append("<%= j render @usuario %>")

app/views/usuarios/destroy.js.erb
$('.delete').bind('ajax:success', function () {
  $(this).closest('tr').remove();
})

app/views/usuarios/edit.html.erb
<% provide(:button_text, 'Editar Usuario') %>
<div class="row justify-content-center">
  <div>
    <h1>Editar Usuario</h1>

    <%= render 'form', usuario: @usuario %>

    <%= link_to 'Show', @usuario %> |
    <%= link_to 'Back', usuarios_path %>
  </div>
</div>

app/views/usuarios/edit.js.erb
$('#new-user').hide().parent().append("<% provide(:button_text, 'Editar Usuario') %> <%= j render 'form', usuario: @usuario %>")

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>
<nav style="display: flex">
  <h1>Usuarios</h1>
  <%= link_to 'New Usuario', new_usuario_path, remote: true, class: "btn btn-primary new-link" %>
</nav>

<div class="table-container row " style="overflow-x:auto;">
  <table id="users">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Correo</th>
        <th>Telefono</th>
        <th>Sexo</th>
        <th>Tipo de usuario</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @usuarios %>
    </tbody>
  </table>
</div>

<br>

<div id="new-user"></div>

app/views/usuarios/new.html.erb
<% provide(:button_text, 'Crear Usuario') %>
<div class="row justify-content-center">
  <div>
    <h1>Nuevo Usuario</h1>
    <%= render 'form', usuario: @usuario %>

    <%= link_to 'Back', usuarios_path %>
  </div>
</div>

app/views/usuarios/new.js.erb
$('.new-link').hide()
$('#new-user').hide().parent().append("<% provide(:button_text, 'Crear Usuario') %> <%= j render 'form', usuario: @usuario %>")

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @usuario.telefono %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @usuario.sexo_id %>
</p>

<p>
  <strong>Tipo de usuario:</strong>
  <%= @usuario.tipo_de_usuario_id %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/update.js.erb
$('.form-container').remove()
$('#new-user').show()
$('#usuario_<%= @usuario.id %>').replaceWith('<%= j render @usuario %>')